services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dulceria_macam
      MYSQL_USER: macamuser
      MYSQL_PASSWORD: macampass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  freeradius:
    build:
      context: .
      dockerfile: freeradius.Dockerfile
    container_name: freeradius
    depends_on:
      - mysql
    environment:
      - RADIUS_DB_HOST=mysql
      - RADIUS_DB_USER=macamuser
      - RADIUS_DB_PASS=macampass
      - RADIUS_DB_NAME=dulceria_macam
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./freeradius/mods-available/sql:/etc/freeradius/mods-available/sql
      - ./wait-for-mysql.sh:/wait-for-mysql.sh
      - ./freeradius/queries.conf:/etc/freeradius/3.0/mods-config/sql/main/mysql/queries.conf
    command: sh -c "chmod 644 /etc/freeradius/mods-available/sql && chmod +x wait-for-mysql.sh && MYSQL_USER=macamuser MYSQL_PASSWORD=macampass MYSQL_DATABASE=dulceria_macam /wait-for-mysql.sh mysql ln -sf /etc/freeradius/mods-available/sql /etc/freeradius/mods-enabled/sql && freeradius -f -X"


  portal:
    build: ./portal
    container_name: portal
    depends_on:
      - freeradius
    ports:
      - "8080:8080"
    environment:
      - RADIUS_HOST=freeradius
      - RADIUS_SECRET=testing123
      - RADIUS_PORT=1812

volumes:
  mysql_data:
