FROM golang:1.24.1-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o portal

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/portal .
COPY --from=builder /app/static ./static
EXPOSE 8080
CMD ["./portal"]
